### PR TITLE
Fix invalid segmentTimes for short videos

### PR DESCRIPTION
**Pull request by pulsejet**
The ffmpeg call fails on short videos without this

### CODE REVIEW

**Comment by pulsejet** [comment]
Sorry about bundling two unrelated changes into one PR (I can separate them it this is a huge problem).

The second commit fixes weird bugs in chrome+videojs probably because of floating point precision. By using integer segment lengths this works wonderfully.

BTW thanks for this wonderful piece of work. I'm currently trying to integrate it with an FOSS Google Photos alternative ([memories](https://github.com/pulsejet/memories)).

**Comment by m1k1o** [comment]
I would separate those two commits:

This commit 3f788ece05fe6dba86997320160cac36850bcd83 is just silencing existing problem that exists. I fixed this issue in ff0709eb9a8fe7d1aae1491d8d552aade0b23488.

The second commit 80ffa0557f7ce5b86629c8088d8d068c96c8cb67 can be merged together with [my latest changes](https://github.com/m1k1o/go-transcode/tree/segment-times) regarding that piece of code.

**Comment by m1k1o** [comment]
Cherry-picked in e07fb5bd1fff67a5b0db76a13d996b6d1985f605. Thank you for your contribution!

**Comment by pulsejet** [comment]
Thank you!

**Pull request closed without merging**
